### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by MicrosoftTakeover** [dkanada/frost#162]
[20190404_105208.zip](https://github.com/dkanada/frost/files/3046570/20190404_105208.zip)
ADB Manager
f.lux
Ghost Commander
Markor
OS Monitor
Scarlet Notes FD
Skytube
Twire
wX

**Comment by MicrosoftTakeover** [comment]
Did most of these of these myself in PR #163
The ones I didn't get around to are Ghost Commander and Scarlet Notes FD.

**Comment by MicrosoftTakeover** [comment]
I think Ghost Commander has a pretty poor icon and would be better off with just using the default "files" icon instead.

**Comment by dkanada** [comment]
Thanks for the new icons! I agree about Ghost Commander, it's not very pretty. You can also  construct your own icon that feels similar to the original and fits this icon set better. I do that relatively often with non-material or complicated icons. Otherwise you can definitely add an entry for Ghost Commander that uses the default files icon.

**Comment by MicrosoftTakeover** [comment]
+Added Scarlet Notes FD and Ghost Commander to PR #163
