### ISSUE TITLE
New F-droid header suggestion

### ISSUE THREAD

**Issue by Donnnno** [dkanada/frost#196]
Hi, I've created a new header image for in the F-droid app. It has a real frosty background now :-) 

![Frost header](https://user-images.githubusercontent.com/31142286/67147230-6af3fd00-f293-11e9-9482-ef755c02d573.png)

**Comment by dkanada** [comment]
I like it! Where did you get the image from?

**Comment by Donnnno** [comment]
Thanks! I downloaded it from Pixabay and it's free to use without attribution.
https://pixabay.com/photos/alpine-allg%C3%A4u-wintry-mountains-4487709/

**Comment by dkanada** [comment]
The header used for GitHub is [here](https://github.com/dkanada/frost/blob/master/metadata/en-US/header-background.png) but if we are changing the main image I'd also like to change the [featureGraphic](https://github.com/dkanada/frost/blob/master/metadata/en-US/featureGraphic.png) used by F-Droid. It might also be useful to generate a new [example list](https://github.com/dkanada/frost/blob/master/metadata/en-US/complete-background.png) just to keep everything uniform.

If you want to submit a pull request with those three images changed I'll merge it. Feel free to change the example list dimensions to fit the page, I made that one in a bit of a rush. We might not even need that image anymore since the header shows people who visit the repository some icons as well.

**Comment by Donnnno** [comment]
Yeah I actually was thinking about the featureGraphic when I said header but I can change the header and example list too. :)
