### ISSUE TITLE
install and use description

### ISSUE THREAD

**Issue by bartatgithub** [dkanada/frost#80]
Hi 

Maybe stupid to ask thru Github but searched the internet and found no help or place to ask. 
I have installed your icon package thru f-droid, after that no way to get it working. 

Maybe put a small text in the 'readme' about install and use? 

LineageOS 14.1
Android 7.1.2

**Comment by ikocevski** [comment]
Hi, Bart. While that's a really good idea I don't think we could be able to cover all the specific setups on all phones. It really depends on the ROM and Android version and the launcher people are using, but thanks for the idea we might do something simpler, like a small guide.

Now for your phone, assuming you use the default LineageOS launcher there should be an option to select an icon pack in the Settings app, look for the Themes menu or something similarly named. Even if you're using a different launcher this setting changes the default to your preferred icon pack and should work globally.

Again, thanks for the idea and if it's still unclear how to switch to Frost, do tell and we'll try and get you a more detailed guide.

**Comment by bartatgithub** [comment]
Thanks. 

Strange, not possible to change icons in LineageOS 14. After searching the net for a time i found only this: https://www.reddit.com/r/LineageOS/comments/6wvo9x/can_we_use_icon_theme_in_trebuchet_in_los14/


And more strange, nobody ask about why LineageOS does that? 

Otherwise i have to change the LineageOS launcher, Trebuchet, but i like Trebuchet.

**Comment by conrad-heimbold** [comment]
@bartatgithub : if you want to use the icons for "folders" (including your apps, draggable as widgets), you can also use 
- Folder Organizer: 
https://play.google.com/store/apps/details?id=com.abcOrganizer.lite (not available on fdroid, free)
https://play.google.com/store/apps/details?id=com.abcOrganizer (costs money, only works with GAPPS) 
- Apps2Org: 
https://f-droid.org/app/com.google.code.apps2org (old) https://f-droid.org/app/com.google.code.appsorganizer (very old)
https://github.com/willemw12/apps2org/releases (new, no fdroid release) 

These apps are also usable **without**  another launcher, because they uses widgets.

**Comment by bartatgithub** [comment]
Thanks, but this seams me 'overkill' to change only the icons. 
Will test i few other launchers and see that i am willing to say good by to Trebuchet. 
Still find it vary strange that an 'open' system like LineageOS don't give a possibility to change the icons in a simpel way.

**Comment by bartatgithub** [comment]
Will close these now, because this is a LineageOS Trebuchet problem. 
Thanks.
